/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmlabelthumbnail_free: (a: number, b: number) => void;
export const __wbg_wasmpayloaddecoderesult_free: (a: number, b: number) => void;
export const buildEcdcProgrammeJson: (a: number, b: number) => [number, number, number, number];
export const buildFixedContextSegmentPlanJson: (a: number, b: number) => [number, number, number, number];
export const buildMultiTrackSegmentBudgetJson: (a: number, b: number) => [number, number, number, number];
export const cacheEncryptionRecordBindingHashHex: (a: number, b: number) => [number, number, number, number];
export const decodeRecordDescriptorHeaderJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const decodeRecordMetadataJson: (a: number, b: number) => [number, number, number, number];
export const decodeRecordPngSidecar: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const decodeRecordPngSidecarItemsJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const decodeRecordPngSidecarJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const decodeRecordPngToPayload: (a: number, b: number) => [number, number, number];
export const decodeRecordPngToPayloadForProfile: (a: number, b: number, c: number, d: number) => [number, number, number];
export const decodeRecordPngToPayloadForProfileWithLength: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const decodeRecordPngToPayloadForProfileWithTurns: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const decodeRecordPngToPayloadForProfileWithTurnsAndLength: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const decodeRecordPngToPayloadWithLength: (a: number, b: number, c: number) => [number, number, number];
export const decodeRecordProgrammeMapJson: (a: number, b: number) => [number, number, number, number];
export const decodeSidecarContainerItemsJson: (a: number, b: number) => [number, number, number, number];
export const decryptCacheEntry: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const encryptCacheEntry: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const extractBitneedlePackageSection: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const extractLabelThumbnail: (a: number, b: number, c: number, d: number) => [number, number, number];
export const inferRecordProfileFromPng: (a: number, b: number) => [number, number, number, number];
export const inspectBitneedlePackageJson: (a: number, b: number) => [number, number, number, number];
export const programmeMapFromChunkStreamJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const recordDescriptorMagic: () => [number, number];
export const recordPngToRgbColorBlockPng: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const recordWasmBuildInfoJson: () => [number, number];
export const validateRecordHeaderJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const validateSidecarContainer: (a: number, b: number) => [number, number, number, number];
export const wasmlabelthumbnail_bytes: (a: number) => [number, number];
export const wasmlabelthumbnail_mime: (a: number) => [number, number];
export const wasmpayloaddecoderesult_chunkStreamBytes: (a: number) => [number, number];
export const wasmpayloaddecoderesult_metadataJson: (a: number) => [number, number];
export const wasmpayloaddecoderesult_payloadBytes: (a: number) => [number, number];
export const wasmpayloaddecoderesult_silenceMapJson: (a: number) => [number, number];
export const initPanicHook: () => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
