/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmrenderresult_free: (a: number, b: number) => void;
export const buildBitneedlePackage: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const buildPackageCoverItemJson: (a: number, b: number) => [number, number];
export const buildPackageDisplayHeader: (a: number, b: number) => [number, number, number, number];
export const buildPackageDisplayHeaderItemJson: (a: number, b: number) => [number, number, number, number];
export const buildPackageMetadataItemsJson: (a: number, b: number) => [number, number, number, number];
export const buildPackagePhotoItemJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const buildPackageSidecarRenderOptionsJson: (a: number, b: number) => [number, number, number, number];
export const buildSidecarContainer: (a: number, b: number) => [number, number, number, number];
export const estimateRecordPngSidecarCapacityJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const extractBitneedlePackageSection: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const inspectBitneedlePackageJson: (a: number, b: number) => [number, number, number, number];
export const normalizeRecordProfileName: (a: number, b: number) => [number, number, number, number];
export const packageFitBudgetJson: (a: number, b: number) => [number, number, number, number];
export const packagePreservedPatternItemsJson: (a: number, b: number) => [number, number, number, number];
export const packageQuantizerSearchPlanJson: (a: number, b: number) => [number, number, number, number];
export const patternizeRecordPngExplore: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const pressCertainLpRecordFormatJson: (a: number, b: number, c: number, d: number, e: number) => [number, number, number, number];
export const pressRecordDurationEstimateJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const pressRecordDurationHintJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const pressRecordFormatRecommendationJson: (a: number, b: number) => [number, number, number, number];
export const recordLabelProfileSpecJson: (a: number, b: number) => [number, number, number, number];
export const recordLabelProfileSpecsJson: () => [number, number, number, number];
export const recordProfileSpecJson: (a: number, b: number) => [number, number, number, number];
export const recordProfileSpecsJson: () => [number, number, number, number];
export const renderEmptyGrooveRecordToPng: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const renderPayloadCodesToPng: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number];
export const renderPayloadContainerToPng: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => [number, number, number];
export const renderPayloadEntriesToPng: (a: any, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number];
export const renderPayloadEntriesWithDescriptorToPng: (a: any, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number];
export const renderRecordProgrammeToPng: (a: any, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number];
export const resolvePackageBestFitCacheKeyJson: (a: number, b: number) => [number, number, number, number];
export const resolvePackageImageEncodeCacheKeyJson: (a: number, b: number) => [number, number, number, number];
export const resolveRecordLabelCutoutStyleJson: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const rewriteRecordPng: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number];
export const visibleSpiralTurns: (a: number, b: number, c: number) => [number, number, number];
export const wasmrenderresult_headerJson: (a: number) => [number, number];
export const wasmrenderresult_payloadJson: (a: number) => [number, number];
export const wasmrenderresult_pngBytes: (a: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
