[workspace]
members = [
  "bitneedle",
  "bytes2rgb",
  "bitneedle-id",
  "record-core",
  "record-cut",
  "record-decode",
  "record-descriptor",
  "record-label",
  "record-groove",
  "record-patternize",
  "record-package",
  "record-render",
  "record-verify",
  "record-sidecar",
  "test-spin",
  "bitneedle-id",
  "record-wasm",
  "record-cut-wasm",
]
resolver = "2"
