[package]
name = "record-descriptor"
version = "0.1.7"
edition = "2021"
description = "bitneedle header formats"
repository = "https://github.com/wavey-ai/bitneedle"
readme = "README.md"
license = "Apache-2.0"

[dependencies]
anyhow = "1"
base64 = "0.22"
brotli = "7"
chacha20poly1305 = { version = "0.10.1", default-features = false, features = ["alloc"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
record-core = { path = "../record-core", version = "0.1.7" }
